### ISSUE TITLE
English stop words contain a tab character in place of a newline

### ISSUE THREAD

**Issue by jkelly-kantar** [astuanax/stopwords#3]
See https://github.com/astuanax/stopwords/blob/master/stopwords/languages/english/default.txt#L99

All the stop words are separated by a new line, apart from 'our' and 'ourselves' which are separated by a tab character (\t).
This means that when you call `stopwords.get_stopwords("en")`, one of the items in the returned list is `'ours\tourselves'` which causes issues with tokenizers (e.g.  [sklearn's CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html), often used for n-grams).

Is this intentional?
I've also noticed it in a few of the other supported languages e.g. [German](https://github.com/astuanax/stopwords/blob/master/stopwords/languages/german/default.txt).

If this is somehow accidental, I'm happy to raise  PR to fix.
Otherwise an explanation would be useful 😄 
For the time being, I can work around this in my own code.

**Comment by chopeen** [comment]
Same problem in the Polish file [default.txt#L100](https://github.com/astuanax/stopwords/blob/master/stopwords/languages/polish/default.txt#L100).

**Comment by astuanax** [comment]
Ok, thx for the report. 
I'll prepare an update in the next week to come

**Comment by astuanax** [comment]
Found the time right now, so updated and made a new release.
thx for the report.
